version: 2
updates:
  - package-ecosystem: maven
    directory: /sms-authenticator
    schedule:
      interval: weekly
    labels:
      - "version-upgrade"
    ignore:
      - dependency-name: org.keycloak:keycloak-quarkus-server-app
      - dependency-name: io.quarkus:quarkus-vertx-http-dev-ui-resources
      - dependency-name: org.apache.maven.plugins:maven-surefire-plugin
      - dependency-name: org.apache.maven.plugins:maven-compiler-plugin
      - dependency-name: io.quarkus:quarkus-maven-plugin
      - dependency-name: org.apache.maven.plugins:maven-assembly-plugin
